### ISSUE TITLE
Icons fail to generate when there are folders matching the extension list

### ISSUE THREAD

**Issue by SanokKule** [rejetto/file-icons#6]
An example:
i have some file in the real folder `assets`
it's located at `c:\...\hfs\assets`
the plugin requests the powershell script to get icon from file
`assets\css\boo.css`
instead of
`c:\...\hfs\assets\css\boo.css`

**Comment by SanokKule** [comment]
After some testing, it seems like this happens if the folder path is relative
![image](https://github.com/user-attachments/assets/2390cd08-f161-4b81-aa1a-8a42a1e507e9)

**Comment by rejetto** [comment]
do you confirm it works if it's not relative?

**Comment by SanokKule** [comment]
Yes

**Comment by rejetto** [comment]
try to change this in file plugin.js:
sampleFiles[ext] = source

into this:
sampleFiles[ext] = api.require('path').resolve(source)

**Comment by SanokKule** [comment]
Yeah now it works

**Comment by SanokKule** [comment]
Although not on all files?

**Comment by SanokKule** [comment]
On subfolders it's missing filename
`Failed to process file: C:\...\hfs\assets\js. Error: Exception calling "ExtractAssociatedIcon" with "1" argument(s): "C:\...\hfs\assets\js"`
Path should be `C:\...\hfs\assets\js\stream.js`

**Comment by SanokKule** [comment]
Seems like path is bad only if the folder name is the same as the extension

**Comment by SanokKule** [comment]
With `.../assets/mkv/test.mkv`
it tries `.../assets/mkv`

If the extension is different, it works

**Comment by SanokKule** [comment]
If the is a file named test.mkv and there is a folder named mkv
```
assets/mkv
assets/test.mkv
```
it fails

**Comment by SanokKule** [comment]
And if the filename doesn't have a space in it?

**Comment by rejetto** [comment]
i'm trying to reproduce 
i made this folder
<img width="189" alt="image" src="https://github.com/user-attachments/assets/7195c725-e533-4442-935e-cac8cfb1a447">

applied the fix above, then put a zip file inside this zip folder.
but when i access it, the icon is good
<img width="328" alt="image" src="https://github.com/user-attachments/assets/e86e6f1a-71bf-4075-b4d6-00e64ebcb545">

what could it be?

**Comment by rejetto** [comment]
> Yeah now it works

in the meantime i've published this fix
